version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: hms_mysql_db
    restart: always
    env_file:
      - ../.env
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./seed_data.sql:/docker-entrypoint-initdb.d/2_seed.sql
      - ./analytics.sql:/docker-entrypoint-initdb.d/3_analytics.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      timeout: 5s
      retries: 5
